services:
  logfindr:
    image: jimamuto/logfindr:latest
    container_name: logfindr
    ports:
      - "8080:8080"
      - "24224:24224"
    volumes:
      - logfindr-data:/data
    restart: unless-stopped

volumes:
  logfindr-data:
