[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /etc/fluent-bit/parsers.conf

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[FILTER]
    Name         modify
    Match        *
    Add          source stdout

[OUTPUT]
    Name         http
    Match        *
    Host         127.0.0.1
    Port         8080
    URI          /ingest
    Format       json
    Json_Date_Key timestamp
    Json_Date_Format iso8601
